import {
  MFY,
  DistrictObject,
  Issue,
  Task,
  InvestmentProject,
  IndustrialZone,
  AuditLogItem,
  SectorIndicator,
  User,
} from '@/types';

export const mockUsers: User[] = [
  {
    id: 'user-hokim',
    name: 'B. Bekmuratov',
    role: 'hokim',
    organization: 'Shomanay rayonı hákimligi',
    title: 'Rayon Hákimi',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-coordinator',
    name: 'A. Qalandarov',
    role: 'coordinator',
    organization: 'Rayon rawajlanıw muwapıqlastırıw bólimi',
    title: 'Bas Koordinator',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-executor',
    name: 'S. Dáwletov',
    role: 'organization',
    organization: 'Rayon Elektr Tarmaqları Kárxanası',
    title: 'Bas Ingener',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-inspector',
    name: 'M. Torebaev',
    role: 'inspector',
    organization: 'Ǵárezsiz Tekseriw & Monitorinq Inspeksiyası',
    title: 'Bas Inspektor',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-stat',
    name: 'G. Allamuratova',
    role: 'statistician',
    organization: 'Shomanay Statistika Bólimi',
    title: 'Statistika Bólimi Baslıǵı',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
];

export const mockMFYs: MFY[] = [
  {
    id: 'mfy-1',
    name: 'Shomanay qalası',
    code: 'SHM-01',
    population: 14850,
    areaSqKm: 8.4,
    centerCoords: [42.6312, 59.1432],
    polygon: [
      [42.642, 59.130],
      [42.645, 59.155],
      [42.625, 59.162],
      [42.618, 59.135],
      [42.642, 59.130],
    ],
    leaderName: 'Q. Yusupov',
    phone: '+998 90 712-44-11',
    activeProjectsCount: 6,
    openIssuesCount: 3,
  },
  {
    id: 'mfy-2',
    name: 'Diyxanabad MPJ',
    code: 'SHM-02',
    population: 8920,
    areaSqKm: 24.5,
    centerCoords: [42.6520, 59.1080],
    polygon: [
      [42.665, 59.085],
      [42.670, 59.130],
      [42.645, 59.132],
      [42.640, 59.090],
      [42.665, 59.085],
    ],
    leaderName: 'R. Begimbetov',
    phone: '+998 91 385-22-90',
    activeProjectsCount: 4,
    openIssuesCount: 2,
  },
  {
    id: 'mfy-3',
    name: 'Begjap MPJ',
    code: 'SHM-03',
    population: 7430,
    areaSqKm: 31.2,
    centerCoords: [42.6120, 59.1850],
    polygon: [
      [42.628, 59.160],
      [42.632, 59.215],
      [42.598, 59.210],
      [42.595, 59.165],
      [42.628, 59.160],
    ],
    leaderName: 'J. Seytniyazov',
    phone: '+998 90 655-10-88',
    activeProjectsCount: 3,
    openIssuesCount: 1,
  },
  {
    id: 'mfy-4',
    name: 'Sarmanbaykól MPJ',
    code: 'SHM-04',
    population: 6850,
    areaSqKm: 42.0,
    centerCoords: [42.5900, 59.1150],
    polygon: [
      [42.615, 59.090],
      [42.618, 59.145],
      [42.570, 59.140],
      [42.565, 59.088],
      [42.615, 59.090],
    ],
    leaderName: 'O. Madreymov',
    phone: '+998 93 420-77-33',
    activeProjectsCount: 3,
    openIssuesCount: 2,
  },
  {
    id: 'mfy-5',
    name: 'Mámıy MPJ',
    code: 'SHM-05',
    population: 5910,
    areaSqKm: 38.6,
    centerCoords: [42.6680, 59.1720],
    polygon: [
      [42.685, 59.145],
      [42.690, 59.198],
      [42.650, 59.195],
      [42.648, 59.142],
      [42.685, 59.145],
    ],
    leaderName: 'B. Kalilaev',
    phone: '+998 91 300-88-21',
    activeProjectsCount: 2,
    openIssuesCount: 1,
  },
  {
    id: 'mfy-6',
    name: 'Aqmashıt MPJ',
    code: 'SHM-06',
    population: 7120,
    areaSqKm: 29.8,
    centerCoords: [42.5750, 59.1820],
    polygon: [
      [42.592, 59.162],
      [42.595, 59.205],
      [42.555, 59.200],
      [42.550, 59.160],
      [42.592, 59.162],
    ],
    leaderName: 'E. Joldasov',
    phone: '+998 90 592-33-14',
    activeProjectsCount: 2,
    openIssuesCount: 1,
  },
];

export const mockObjects: DistrictObject[] = [
  {
    id: 'obj-1',
    name: '«Shomanay Paxta Klasteri» QK',
    type: 'enterprise',
    mfyId: 'mfy-1',
    address: 'Shomanay qalası, Sanaat kóshesi 12',
    coords: [42.6345, 59.1478],
    responsibleOrg: 'Qaraqalpaq-Agro Holding',
    curator: 'T. Allaniyazov',
    status: 'active',
    source: 'Rayon Statistika & Kárxanalar Reestri',
    updatedDate: '2026-09-28',
    description: 'Paxtanı qayta islew, jip-yigiruv hám tekstil mahsulotları islep shıǵarıw boyınsha iri kárxana.',
    photos: [
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=800&auto=format&fit=crop&q=80',
    ],
    documents: [
      { title: 'Gúwalıq hám Litsenziya', date: '2024-03-15', size: '2.4 MB', type: 'PDF' },
      { title: 'Quwatlılıq pasportı', date: '2026-01-10', size: '1.8 MB', type: 'PDF' },
    ],
    capacity: {
      total: 35000,
      used: 28500,
      free: 6500,
      unit: 'tonna paxta/jıl',
      resourceType: 'Paxta xom-ashyosi',
    },
    metrics: {
      revenueMlnUzs: 48500,
      jobs: 320,
      exportVolumeUsd: 2150000,
      progressPercent: 92,
    },
    relatedIssuesCount: 1,
    relatedTasksCount: 1,
  },
  {
    id: 'obj-2',
    name: 'Zamonaviy Gidroponika Issıqxana Kompleksi',
    type: 'investment_project',
    mfyId: 'mfy-2',
    address: 'Diyxanabad MPJ, Dala uchastkası 44',
    coords: [42.6540, 59.1050],
    responsibleOrg: '«Shomanay Agro Eksport» JShJ',
    curator: 'K. Sarsenbaev',
    status: 'risk',
    source: 'Investiciyalar bólimi',
    updatedDate: '2026-09-29',
    description: '5 gektar maydonda pomidor hám qıyar jetistiriwshi zamanagóy issıqxana. Gaz basımı tómenligi sebepli keshigiw bar.',
    photos: [
      'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?w=800&auto=format&fit=crop&q=80',
    ],
    documents: [
      { title: 'Issıqxana Joybar-Smeta Hújjeti', date: '2025-11-20', size: '5.1 MB', type: 'PDF' },
      { title: 'Gaz tarmaǵına qosılıw akti', date: '2026-08-12', size: '1.2 MB', type: 'PDF' },
    ],
    capacity: {
      total: 1200,
      used: 650,
      free: 550,
      unit: 'tonna ónim/jıl',
      resourceType: 'Oqshovlanǵan gaz/issiqlik',
    },
    metrics: {
      revenueMlnUzs: 14200,
      jobs: 65,
      exportVolumeUsd: 850000,
      progressPercent: 78,
    },
    relatedIssuesCount: 2,
    relatedTasksCount: 2,
  },
  {
    id: 'obj-3',
    name: 'Shomanay Kishi Sanaat Zonası (KSZ)',
    type: 'industrial_zone',
    mfyId: 'mfy-1',
    address: 'Shomanay qalası, Qubla sanaat maydanı',
    coords: [42.6240, 59.1380],
    responsibleOrg: 'Rayon Hákimligi KSZ Direksiyası',
    curator: 'A. Qalandarov',
    status: 'active',
    source: 'KSZ Direksiyası',
    updatedDate: '2026-09-30',
    description: '14.5 gektar maydonda ornalasqan kishi sanaat zonası. Qurılıs materialları hám jeńil sanaat joybarları ushın.',
    photos: [
      'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f9?w=800&auto=format&fit=crop&q=80',
    ],
    documents: [
      { title: 'KSZ Master-rejisi', date: '2024-05-18', size: '14.0 MB', type: 'PDF' },
      { title: 'Infratuzilma quwatlılıqları tastıyıǵı', date: '2026-06-01', size: '2.9 MB', type: 'PDF' },
    ],
    capacity: {
      total: 14.5,
      used: 9.2,
      free: 5.3,
      unit: 'gektar',
      resourceType: 'Yer maydanı',
    },
    metrics: {
      revenueMlnUzs: 32600,
      jobs: 210,
      exportVolumeUsd: 920000,
      progressPercent: 88,
    },
    relatedIssuesCount: 1,
    relatedTasksCount: 1,
  },
  {
    id: 'obj-4',
    name: '«Shomanay 110/35/10 kV» Oraylıq Podstanciyası',
    type: 'infrastructure',
    mfyId: 'mfy-3',
    address: 'Begjap MPJ, Energetikler aymaǵı',
    coords: [42.6180, 59.1790],
    responsibleOrg: 'Qaraqalpaqstan Elektr Tarmaqları AJ',
    curator: 'S. Dáwletov',
    status: 'active',
    source: 'Rayon Elektr Tarmaqları',
    updatedDate: '2026-09-25',
    description: 'Rayon orayı hám qonshı awıllardı elektr energiyası menen támiyinlewshi tiykarǵı energetika túyini.',
    photos: [
      'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?w=800&auto=format&fit=crop&q=80',
    ],
    documents: [
      { title: 'Podstansiya texnik pasportı', date: '2023-09-10', size: '4.2 MB', type: 'PDF' },
    ],
    capacity: {
      total: 32,
      used: 26.5,
      free: 5.5,
      unit: 'MWt',
      resourceType: 'Elektr quwatı',
    },
    metrics: {
      progressPercent: 100,
    },
    relatedIssuesCount: 1,
    relatedTasksCount: 1,
  },
  {
    id: 'obj-5',
    name: 'Súwti Qayta Islew & Pishloq Zavodı',
    type: 'investment_project',
    mfyId: 'mfy-4',
    address: 'Sarmanbaykól MPJ, Shárwa ferması janında',
    coords: [42.5920, 59.1210],
    responsibleOrg: '«Arallıq Sút Ónimleri» ShJ',
    curator: 'J. Seytniyazov',
    status: 'in_progress',
    source: 'Investiciya portalı',
    updatedDate: '2026-09-28',
    description: 'Sút qabıllaw punktleri hám tábiyiy pishloq, qatıq islep shıǵarıw zavodı.',
    photos: [
      'https://images.unsplash.com/photo-1527153857715-3908f2ae5e81?w=800&auto=format&fit=crop&q=80',
    ],
    documents: [
      { title: 'Zavod texnologik liniyası', date: '2025-08-14', size: '3.6 MB', type: 'PDF' },
    ],
    capacity: {
      total: 20,
      used: 12,
      free: 8,
      unit: 'tonna sút/kún',
      resourceType: 'Sút qabıllaw',
    },
    metrics: {
      revenueMlnUzs: 8400,
      jobs: 45,
      progressPercent: 65,
    },
    relatedIssuesCount: 0,
    relatedTasksCount: 1,
  },
  {
    id: 'obj-6',
    name: 'Rayon Oraylıq Kóp Tarmaqlı Poliklinikası',
    type: 'social',
    mfyId: 'mfy-1',
    address: 'Shomanay qalası, Berdaq kóshesi 5',
    coords: [42.6370, 59.1410],
    responsibleOrg: 'Rayon Medicina Birlespesi',
    curator: 'Z. Nurjanova',
    status: 'active',
    source: 'Densawlıqtı saqlaw bólimi',
    updatedDate: '2026-09-15',
    description: 'Kúndizgi qabıllaw quwatı 250 nawqas bolǵan zamanagóy oraylıq poliklinika.',
    photos: [
      'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80',
    ],
    documents: [
      { title: 'Medicinalıq akkreditaciya', date: '2024-02-28', size: '1.5 MB', type: 'PDF' },
    ],
    capacity: {
      total: 250,
      used: 210,
      free: 40,
      unit: 'orın/kún',
      resourceType: 'Qabıllaw quwatı',
    },
    metrics: {
      progressPercent: 100,
    },
    relatedIssuesCount: 0,
    relatedTasksCount: 0,
  },
  {
    id: 'obj-7',
    name: 'Qaraqalpaq Gaz Taqsimlaw Tarmaǵı «Shomanay-Diyxanabad»',
    type: 'infrastructure',
    mfyId: 'mfy-2',
    address: 'Diyxanabad baǵdarı, GRS-3',
    coords: [42.6480, 59.1120],
    responsibleOrg: '«Hududgaz Qaraqalpaqstan» Gaz Támiynatı',
    curator: 'M. Orazbaev',
    status: 'risk',
    source: 'Rayon Gaz Xızmeti',
    updatedDate: '2026-09-29',
    description: 'Issıqxana kompleksleri hám xalıq ushın tábiyiy gaz basımın turaqlı támiyinlewshi tarmaq.',
    photos: [
      'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&auto=format&fit=crop&q=80',
    ],
    documents: [
      { title: 'Gaz tarmog‘i rekonstruksiya loyihasi', date: '2026-04-10', size: '3.1 MB', type: 'PDF' },
    ],
    capacity: {
      total: 12000,
      used: 11400,
      free: 600,
      unit: 'm³/saat',
      resourceType: 'Gaz ótkiziw quwatı',
    },
    metrics: {
      progressPercent: 45,
    },
    relatedIssuesCount: 1,
    relatedTasksCount: 1,
  },
  {
    id: 'obj-8',
    name: '«Shomanay Keramika Plitkalari» Zavodi',
    type: 'investment_project',
    mfyId: 'mfy-5',
    address: 'Mámıy MPJ, Sanaat uchastkasi 8',
    coords: [42.6640, 59.1680],
    responsibleOrg: '«Karakalpak Ceramic Group»',
    curator: 'B. Kalilaev',
    status: 'in_progress',
    source: 'Rayon Investiciya Basqarması',
    updatedDate: '2026-09-28',
    description: 'Jergilikli qum hám gips xom-ashyosı tiykarında kafeller hám fasad plitkalari islep shıǵarıw zavodı.',
    photos: [
      'https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800&auto=format&fit=crop&q=80',
    ],
    documents: [
      { title: 'Ekologiyalıq ekspertiza qorıtyndısı', date: '2025-10-05', size: '2.1 MB', type: 'PDF' },
    ],
    capacity: {
      total: 450000,
      used: 180000,
      free: 270000,
      unit: 'm²/jıl',
      resourceType: 'Plitka islep shıǵarıw',
    },
    metrics: {
      revenueMlnUzs: 18900,
      jobs: 90,
      progressPercent: 70,
    },
    relatedIssuesCount: 1,
    relatedTasksCount: 1,
  },
];

export const mockIssues: Issue[] = [
  {
    id: 'iss-1',
    code: 'MSH-2026-081',
    title: 'Gidroponika issıqxanasına gaz basımı jetispewshiligi',
    description: 'Diyxanabad MPJ daǵı zamonaviy issıqxana kompleksinde gaz basımı 0.8 atm ga túsip ketken, joybar boyınsha 2.2 atm kerek. Ekinler nobud bolıw qáwpi bar.',
    category: 'gas',
    priority: 'critical',
    objectId: 'obj-2',
    objectName: 'Zamonaviy Gidroponika Issıqxana Kompleksi',
    mfyId: 'mfy-2',
    source: 'auto_rule',
    reportedDate: '2026-09-22',
    status: 'assigned',
    relatedIndicator: 'Sanoat va agrosanoat ishlab chiqarish hajmi',
    assignedTaskId: 'tsk-101',
    reportedBy: 'K. Sarsenbaev (Tashkilot mas\'uli)',
    evidenceNotes: 'Gaz sayǵısh kórsetkishleri hám avtomatika datchik signalı tirkelgen.',
  },
  {
    id: 'iss-2',
    code: 'MSH-2026-082',
    title: 'KSZ aymaǵında 10 kV qosımsha podstanciya qurılısı keshigiwi',
    description: 'Shomanay KSZ daǵı jańa 3 kárxana ushın zárúr 1.5 MWt quwatlılıqtaǵı transformator ornatıw rejesi 14 kúnge keshikpekte.',
    category: 'electricity',
    priority: 'high',
    objectId: 'obj-3',
    objectName: 'Shomanay Kishi Sanaat Zonası (KSZ)',
    mfyId: 'mfy-1',
    source: 'manual',
    reportedDate: '2026-09-24',
    status: 'in_progress',
    relatedIndicator: 'Yangi quvvatlarni ishga tushirish',
    assignedTaskId: 'tsk-102',
    reportedBy: 'A. Qalandarov (Koordinator)',
  },
  {
    id: 'iss-3',
    code: 'MSH-2026-083',
    title: 'Sarmanbaykól MPJ oraylıq avtomobil jolınıń oypatlıqları',
    description: 'Sút zavodına kiretuǵın 2.4 km asfalt jolda awır júk mashinaları qatnawı sebepli joldıń buzılıwı hám sút tasiwde mashqala payda bolǵan.',
    category: 'road_transport',
    priority: 'medium',
    objectId: 'obj-5',
    objectName: 'Súwti Qayta Islew & Pishloq Zavodı',
    mfyId: 'mfy-4',
    source: 'citizen_appeal',
    reportedDate: '2026-09-25',
    status: 'under_review',
    assignedTaskId: 'tsk-103',
    reportedBy: 'O. Madreymov (MPJ Baslıǵı)',
  },
  {
    id: 'iss-4',
    code: 'MSH-2026-084',
    title: '«Shomanay Paxta Klasteri» ushın toqımashılıq qánigeleri jetispewshiligi',
    description: 'Kárxana jańa liniyası ushın 40 nafar joqarı qánigeli toqımashı hám sozıwshı usta talap etiledi, rayondaǵı kásip-óner mektebi bitiriwshileri qánigeligi tolıq sáykes emes.',
    category: 'labor_skills',
    priority: 'medium',
    objectId: 'obj-1',
    objectName: '«Shomanay Paxta Klasteri» QK',
    mfyId: 'mfy-1',
    source: 'statistic_alert',
    reportedDate: '2026-09-26',
    status: 'assigned',
    assignedTaskId: 'tsk-104',
    reportedBy: 'G. Allamuratova (Statistik)',
  },
  {
    id: 'iss-5',
    code: 'MSH-2026-085',
    title: 'Keramika zavodına texnikalıq suw tarmog‘ın tartıw',
    description: 'Zavod qurılıs maydanına kerekli kúnine 80 m³ texnikalıq suw quwırın ulastırıw boyınsha geodeziya kelisimi toqtap qalǵan.',
    category: 'water',
    priority: 'high',
    objectId: 'obj-8',
    objectName: '«Shomanay Keramika Plitkalari» Zavodi',
    mfyId: 'mfy-5',
    source: 'manual',
    reportedDate: '2026-09-27',
    status: 'open',
    reportedBy: 'B. Kalilaev (MPJ Baslıǵı)',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'tsk-101',
    code: 'TAP-2026-001',
    issueId: 'iss-1',
    objectId: 'obj-2',
    objectName: 'Zamonaviy Gidroponika Issıqxana Kompleksi',
    mfyId: 'mfy-2',
    title: 'Diyxanabad issıqxanasına gaz basımın 2.2 atm ǵa kóteriw',
    actionDescription: 'GRS-3 ten issıqxanaǵacha bolǵan 800 metr trubanı diametri 159 mm bolǵan jańa liniyaǵa almastırıw hám basımdı turaqlı saqlaw.',
    mainExecutorOrg: '«Hududgaz Qaraqalpaqstan» Gaz Támiynatı',
    executorPerson: 'M. Orazbaev',
    inspectorOrg: 'Ǵárezsiz Tekseriw & Monitorinq Inspeksiyası',
    inspectorPerson: 'M. Torebaev',
    status: 'in_progress',
    priority: 'critical',
    createdDate: '2026-09-23',
    deadline: '2026-10-02T18:00:00+05:00',
    expectedResult: 'Gaz basımınıń 2.2 atm bolıwı hám akt dúziliwi',
    verificationMethod: 'Basım manometri fiksaciyası, foto hám eki tárepleme qabıllaw akti',
    extensions: [],
    isOverdue: false,
    evidence: {
      submittedAt: '2026-09-29T16:30:00+05:00',
      submittedBy: 'M. Orazbaev',
      comment: 'Truba montaj jumısları 80% pitkerildi, sınaq isleri baslandı.',
      numericResult: 1.8,
      unit: 'atm',
      photos: [
        'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
      ],
      documents: [
        { name: 'Diyxanabad_Gaz_Ornatuv_Akti.pdf', size: '1.4 MB', type: 'PDF' },
      ],
    },
    postExecutionMeasurement: {
      baselineValue: 0.8,
      targetValue: 2.2,
      actualMeasuredValue: 1.8,
      unit: 'atm',
      measurementPeriod: '1 hápte',
      responsiblePerson: 'M. Torebaev',
      verified: false,
    },
  },
  {
    id: 'tsk-102',
    code: 'TAP-2026-002',
    issueId: 'iss-2',
    objectId: 'obj-3',
    objectName: 'Shomanay Kishi Sanaat Zonası (KSZ)',
    mfyId: 'mfy-1',
    title: 'KSZ aymaǵında 1.5 MWt transformatordı ornatıw hám iske túsiriw',
    actionDescription: 'Elektr tarmaqları kárxanası tárepinen transformator punktti ornatıw, kabel liniyaların tartıw hám kárxanalardı ulastırıw.',
    mainExecutorOrg: 'Rayon Elektr Tarmaqları Kárxanası',
    executorPerson: 'S. Dáwletov',
    inspectorOrg: 'Ǵárezsiz Tekseriw & Monitorinq Inspeksiyası',
    inspectorPerson: 'M. Torebaev',
    status: 'under_review',
    priority: 'high',
    createdDate: '2026-09-20',
    deadline: '2026-09-28T18:00:00+05:00',
    expectedResult: 'Transformator ornatılıp, 3 jańa kárxanaǵa elektr beriliwi',
    verificationMethod: 'Elektr támiynatı qosılıw akti, texnik sinov jurnalı hám foto dalil',
    extensions: [
      {
        id: 'ext-1',
        oldDeadline: '2026-09-24T18:00:00+05:00',
        newDeadline: '2026-09-28T18:00:00+05:00',
        reason: 'Qosımsha kabel materialları Nókis qalasınan keshigip jetkerilgenligi sebepli',
        approvedBy: 'B. Bekmuratov (Hákim)',
        approvedDate: '2026-09-23',
      },
    ],
    isOverdue: true, // September 28 passed, current date is Sept 30, 2026
    evidence: {
      submittedAt: '2026-09-29T11:20:00+05:00',
      submittedBy: 'S. Dáwletov',
      comment: 'Transformator tolıq ornatıldı, tok berildi, 3 kárxana ulandı.',
      numericResult: 1.5,
      unit: 'MWt',
      photos: [
        'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&auto=format&fit=crop&q=80',
      ],
      documents: [
        { name: 'Transformator_Sınaq_Hújjeti.pdf', size: '2.1 MB', type: 'PDF' },
        { name: 'Kárxanalardı_Ulastırıw_Akti.pdf', size: '1.7 MB', type: 'PDF' },
      ],
    },
    postExecutionMeasurement: {
      baselineValue: 0,
      targetValue: 1.5,
      actualMeasuredValue: 1.5,
      unit: 'MWt',
      measurementPeriod: '1 ay',
      responsiblePerson: 'M. Torebaev',
      verified: false,
    },
  },
  {
    id: 'tsk-103',
    code: 'TAP-2026-003',
    issueId: 'iss-3',
    objectId: 'obj-5',
    objectName: 'Súwti Qayta Islew & Pishloq Zavodı',
    mfyId: 'mfy-4',
    title: 'Sarmanbaykól joliniń 2.4 km bólegin turaqlı ońlaw (sheben hám asfalt basıw)',
    actionDescription: 'Jol ońlaw unitar kárxanası tárepinen asfalt qatlamın jańalaw hám jol shetlerin bekkemlew.',
    mainExecutorOrg: 'Shomanay Rayon Jol Ońlaw Basqarması',
    executorPerson: 'Q. Xojaniyazov',
    inspectorOrg: 'Ǵárezsiz Tekseriw & Monitorinq Inspeksiyası',
    inspectorPerson: 'M. Torebaev',
    status: 'under_review',
    priority: 'medium',
    createdDate: '2026-09-18',
    deadline: '2026-09-29T18:00:00+05:00',
    expectedResult: '2.4 km jol tolıq ońlanıwı hám sút tasıw mashinaları qatnawınıń tikleniwi',
    verificationMethod: 'Jol qabıllaw komissiyası dalalatnaması, GPS trek hám foto esabat',
    extensions: [],
    isOverdue: true,
    evidence: {
      submittedAt: '2026-09-29T18:00:00+05:00',
      submittedBy: 'Q. Xojaniyazov',
      comment: 'Asfalt jayıw jumısları 2.4 km aralıqta juwmaqlandı. Qabıl etiw soraladı.',
      numericResult: 2.4,
      unit: 'km',
      photos: [
        'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f9?w=800&auto=format&fit=crop&q=80',
      ],
      documents: [
        { name: 'Sarmanbaykol_Jol_Qabıllaw_Akti.pdf', size: '2.8 MB', type: 'PDF' },
      ],
    },
  },
  {
    id: 'tsk-104',
    code: 'TAP-2026-004',
    issueId: 'iss-4',
    objectId: 'obj-1',
    objectName: '«Shomanay Paxta Klasteri» QK',
    mfyId: 'mfy-1',
    title: 'Toqımashılıq kásip-óneri boyınsha 40 nafar jaslardı qısqa múddetli orqalı oqıtıw',
    actionDescription: 'Kambagallikti qısqartıw hám bántlik bólimi menen birgelikte klaster talabı boyınsha oqıtıw shólkemlestiriw.',
    mainExecutorOrg: 'Rayon Kambagallikti Qısqartıw & Bántlik Bólimi',
    executorPerson: 'R. Nurımbetov',
    inspectorOrg: 'Shomanay rayonı hákimligi',
    inspectorPerson: 'A. Qalandarov',
    status: 'accepted',
    priority: 'medium',
    createdDate: '2026-09-01',
    deadline: '2026-09-25T18:00:00+05:00',
    completedDate: '2026-09-24',
    expectedResult: '40 nafar kásip iyesi tayarlanıp, klasterǵa jumısqa qabıl etiliwi',
    verificationMethod: 'Sertifikatlar reestri, miynet shártnamaları nusqası',
    extensions: [],
    isOverdue: false,
    evidence: {
      submittedAt: '2026-09-23T14:10:00+05:00',
      submittedBy: 'R. Nurımbetov',
      comment: '40 nafar pútkeriwshige sertifikat tapsırıldı hám olar klasterge jumısqa kirdi.',
      numericResult: 40,
      unit: 'adam',
      photos: [
        'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80',
      ],
      documents: [
        { name: 'Toqımashı_Pútkeriwshiler_Reestri.pdf', size: '1.1 MB', type: 'PDF' },
      ],
    },
    review: {
      reviewedAt: '2026-09-24T10:00:00+05:00',
      reviewedBy: 'A. Qalandarov',
      accepted: true,
      inspectorNotes: 'Hújjetler tekserildi, klaster tárepinen 40 adam jumısqa alınǵanlıǵı tastıyıqlandı.',
    },
  },
  {
    id: 'tsk-105',
    code: 'TAP-2026-005',
    objectId: 'obj-8',
    objectName: '«Shomanay Keramika Plitkalari» Zavodi',
    mfyId: 'mfy-5',
    title: 'Keramika zavodına texnikalıq suw tarmog‘ın tartıw hám suw rezervuarın qurıw',
    actionDescription: 'Suw támiynatı kárxanası tárepinen 1.8 km truba montajlanıp, 200 m³ lıq rezervuar qurılısı juwmaqlanıwı kerek.',
    mainExecutorOrg: '«Qaraqalpaq Suw Támiynatı» Shomanay filialı',
    executorPerson: 'E. Jumanazarov',
    inspectorOrg: 'Ǵárezsiz Tekseriw & Monitorinq Inspeksiyası',
    inspectorPerson: 'M. Torebaev',
    status: 'assigned',
    priority: 'high',
    createdDate: '2026-09-28',
    deadline: '2026-10-15T18:00:00+05:00',
    expectedResult: 'Texnikalıq suw támiynatı ornatılıp, sutkasına 80 m³ suw beriliwi',
    verificationMethod: 'Suw ólshew esaplaǵıshı akti hám fotohújjet',
    extensions: [],
    isOverdue: false,
  },
];

export const mockInvestments: InvestmentProject[] = [
  {
    id: 'inv-1',
    name: 'Zamonaviy Gidroponika Issıqxana Kompleksi (5 Ga)',
    investorName: '«Shomanay Agro Eksport» JShJ',
    directionSector: 'Awıl xojalıǵı & Agrosanaat',
    objectId: 'obj-2',
    mfyId: 'mfy-2',
    totalCostMlnUzs: 24500,
    foreignInvestThousandUsd: 1200,
    stage: 'construction',
    plannedLaunchDate: '2026-11-20',
    plannedJobs: 80,
    reportedJobs: 65,
    verifiedJobs: 50,
    financialProgressPercent: 82, // Moliyaviy o'zlashtirish
    physicalProgressPercent: 70,  // Fizik tayyorgarlik (farq bar!)
    milestones: [
      { id: 'm-1', title: 'Jer maydanın tayarlaw hám tegislew', weightPercent: 15, plannedDate: '2026-02-15', actualDate: '2026-02-10', status: 'completed' },
      { id: 'm-2', title: 'Issıqxana metall konstruksiyaların montajlaw', weightPercent: 25, plannedDate: '2026-05-30', actualDate: '2026-05-28', status: 'completed' },
      { id: 'm-3', title: 'Gidroponika uskunaları hám kompyuter basqarıwın ornatıw', weightPercent: 30, plannedDate: '2026-08-20', actualDate: '2026-08-30', status: 'completed' },
      { id: 'm-4', title: 'Gaz hám ıssılıq támiynatın ornatıw', weightPercent: 20, plannedDate: '2026-09-25', status: 'delayed' },
      { id: 'm-5', title: 'Eginlerdi egiw hám sınaqtan ótkeriw', weightPercent: 10, plannedDate: '2026-11-15', status: 'pending' },
    ],
    infrastructureNeeds: {
      electricityKva: 450,
      gasM3PerHour: 1800,
      waterM3PerDay: 120,
      landHa: 5.0,
      status: 'deficit_risk',
    },
    exportPotentialThousandUsd: 850,
    annualTaxPotentialMlnUzs: 1400,
    relatedTasksCount: 2,
  },
  {
    id: 'inv-2',
    name: '«Shomanay Paxta Klasteri» Tekstil İplik Fazası-2',
    investorName: 'Qaraqalpaq-Agro Holding',
    directionSector: 'Jeńil sanaat & Tekstil',
    objectId: 'obj-1',
    mfyId: 'mfy-1',
    totalCostMlnUzs: 62000,
    foreignInvestThousandUsd: 3800,
    stage: 'equipment_installation',
    plannedLaunchDate: '2026-12-10',
    plannedJobs: 250,
    reportedJobs: 210,
    verifiedJobs: 195,
    financialProgressPercent: 90,
    physicalProgressPercent: 88,
    milestones: [
      { id: 'm-21', title: 'Tiykarǵı sanaat korpusı qurılısı', weightPercent: 30, plannedDate: '2025-12-01', actualDate: '2025-11-20', status: 'completed' },
      { id: 'm-22', title: 'Germaniya Rieter jip-yigiruv stanokların keltiriw', weightPercent: 40, plannedDate: '2026-06-15', actualDate: '2026-06-25', status: 'completed' },
      { id: 'm-23', title: 'Uskunalardı sozıw hám elektro-avtomatika', weightPercent: 20, plannedDate: '2026-10-15', status: 'in_progress' },
      { id: 'm-24', title: 'Sınaq islep shıǵarıw hám sertifikatlaw', weightPercent: 10, plannedDate: '2026-11-30', status: 'pending' },
    ],
    infrastructureNeeds: {
      electricityKva: 2200,
      gasM3PerHour: 600,
      waterM3PerDay: 180,
      landHa: 3.2,
      status: 'satisfied',
    },
    exportPotentialThousandUsd: 4200,
    annualTaxPotentialMlnUzs: 4800,
    relatedTasksCount: 1,
  },
  {
    id: 'inv-3',
    name: '«Shomanay Keramika Plitkalari» Zavodi',
    investorName: '«Karakalpak Ceramic Group»',
    directionSector: 'Qurılıs materialları sanaatı',
    objectId: 'obj-8',
    mfyId: 'mfy-5',
    totalCostMlnUzs: 38000,
    foreignInvestThousandUsd: 2100,
    stage: 'construction',
    plannedLaunchDate: '2027-03-15',
    plannedJobs: 120,
    reportedJobs: 80,
    verifiedJobs: 65,
    financialProgressPercent: 68,
    physicalProgressPercent: 54,
    milestones: [
      { id: 'm-31', title: 'Zavod binasi karkası hám poydevori', weightPercent: 30, plannedDate: '2026-05-20', actualDate: '2026-05-18', status: 'completed' },
      { id: 'm-32', title: 'Italiya klinker pechlari uskunasın qabıllaw', weightPercent: 35, plannedDate: '2026-09-30', status: 'in_progress' },
      { id: 'm-33', title: 'Texnikalıq suw hám gaz tarmaǵın ulastırıw', weightPercent: 20, plannedDate: '2026-11-20', status: 'pending' },
      { id: 'm-34', title: 'Ichki bezatish hám iske qosıw', weightPercent: 15, plannedDate: '2027-02-28', status: 'pending' },
    ],
    infrastructureNeeds: {
      electricityKva: 1600,
      gasM3PerHour: 2200,
      waterM3PerDay: 100,
      landHa: 4.8,
      status: 'in_process',
    },
    exportPotentialThousandUsd: 1500,
    annualTaxPotentialMlnUzs: 2600,
    relatedTasksCount: 2,
  },
  {
    id: 'inv-4',
    name: '«Arallıq Sút Ónimleri» Pishloq Zavodı',
    investorName: '«Arallıq Sút Ónimleri» ShJ',
    directionSector: 'Aziq-awqat sanaatı',
    objectId: 'obj-5',
    mfyId: 'mfy-4',
    totalCostMlnUzs: 12800,
    foreignInvestThousandUsd: 650,
    stage: 'launch_ready',
    plannedLaunchDate: '2026-10-15',
    plannedJobs: 55,
    reportedJobs: 45,
    verifiedJobs: 45,
    financialProgressPercent: 95,
    physicalProgressPercent: 92,
    milestones: [
      { id: 'm-41', title: 'Sút qabıllaw binosı hám laboratoriya', weightPercent: 35, plannedDate: '2026-03-30', actualDate: '2026-03-25', status: 'completed' },
      { id: 'm-42', title: 'Pasterizator hám pishloq pishiriw qazoni', weightPercent: 35, plannedDate: '2026-07-20', actualDate: '2026-07-18', status: 'completed' },
      { id: 'm-43', title: 'Avtomobil jolin ta\'mirlash', weightPercent: 20, plannedDate: '2026-09-25', status: 'delayed' },
      { id: 'm-44', title: 'Sanitariya litsenziyasi hám test partiyasi', weightPercent: 10, plannedDate: '2026-10-10', status: 'pending' },
    ],
    infrastructureNeeds: {
      electricityKva: 350,
      gasM3PerHour: 300,
      waterM3PerDay: 80,
      landHa: 1.5,
      status: 'satisfied',
    },
    exportPotentialThousandUsd: 400,
    annualTaxPotentialMlnUzs: 950,
    relatedTasksCount: 1,
  },
];

export const mockIndustrialZones: IndustrialZone[] = [
  {
    id: 'iz-1',
    name: 'Shomanay Kishi Sanaat Zonası (KSZ)',
    type: 'KSZ',
    mfyId: 'mfy-1',
    totalAreaHa: 14.5,
    occupiedAreaHa: 9.2,
    freeAreaHa: 5.3,
    activeCompaniesCount: 12,
    totalInvestmentMlnUzs: 54000,
    totalJobs: 340,
    capacities: {
      electricityMwt: { total: 6.0, used: 4.5, free: 1.5 },
      gasM3H: { total: 4500, used: 3600, free: 900 },
      waterM3Day: { total: 350, used: 220, free: 130 },
      sewageAvailable: true,
      railwayConnected: false,
      asphaltRoad: true,
    },
    coords: [42.6240, 59.1380],
  },
  {
    id: 'iz-2',
    name: 'Diyxanabad Agrologistika & Qayta Islew Parki',
    type: 'Agrologistika',
    mfyId: 'mfy-2',
    totalAreaHa: 22.0,
    occupiedAreaHa: 11.5,
    freeAreaHa: 10.5,
    activeCompaniesCount: 6,
    totalInvestmentMlnUzs: 38500,
    totalJobs: 180,
    capacities: {
      electricityMwt: { total: 4.0, used: 2.8, free: 1.2 },
      gasM3H: { total: 6000, used: 5500, free: 500 }, // Gas tight!
      waterM3Day: { total: 500, used: 310, free: 190 },
      sewageAvailable: true,
      railwayConnected: true,
      asphaltRoad: true,
    },
    coords: [42.6560, 59.1020],
  },
];

export const mockAuditLogs: AuditLogItem[] = [
  {
    id: 'aud-1',
    timestamp: '2026-09-30 11:42:15',
    userName: 'A. Qalandarov (Koordinator)',
    userRole: 'coordinator',
    action: 'Múddetti uzaytıw tastıyıqlandı',
    entityType: 'task',
    entityId: 'tsk-102',
    entityName: 'KSZ transformatordı ornatıw',
    changes: [
      { field: 'deadline', oldValue: '2026-09-24', newValue: '2026-09-28' },
      { field: 'status', oldValue: 'in_progress', newValue: 'under_review' },
    ],
    reason: 'Kabel jetkeriw keshigiwi boyınsha hákim kelisimi tiykarında',
    ipAddress: '195.158.12.84',
  },
  {
    id: 'aud-2',
    timestamp: '2026-09-29 16:30:10',
    userName: 'M. Orazbaev (Hududgaz)',
    userRole: 'organization',
    action: 'Dálil hújjetleri biriktirildi',
    entityType: 'task',
    entityId: 'tsk-101',
    entityName: 'Diyxanabad issıqxanası gaz basımı',
    changes: [
      { field: 'evidence.photos', oldValue: '0 fayl', newValue: '1 fayl' },
      { field: 'numericResult', oldValue: '0.8 atm', newValue: '1.8 atm' },
    ],
    reason: 'Truba montajı orınlanǵanlıǵı haqqında foto hám akt',
    ipAddress: '84.54.91.22',
  },
  {
    id: 'aud-3',
    timestamp: '2026-09-28 09:15:40',
    userName: 'G. Allamuratova (Statistika)',
    userRole: 'statistician',
    action: 'Excel import orqalı ko‘rsatkichlar jańalandı',
    entityType: 'import',
    entityId: 'imp-2026-09',
    entityName: 'Shomanay 2026-jıl 9-ay kórsetkishleri',
    changes: [
      { field: 'sanat_hajmi', oldValue: '312.4 mlrd', newValue: '338.9 mlrd' },
      { field: 'yangi_ish_orunlari', oldValue: '1240', newValue: '1385' },
    ],
    reason: 'Rayon statistika bólimi 3-sherek juwmaǵı boyınsha',
    ipAddress: '195.158.14.19',
  },
  {
    id: 'aud-4',
    timestamp: '2026-09-24 10:00:15',
    userName: 'A. Qalandarov (Hákimlik)',
    userRole: 'coordinator',
    action: 'Tapsırma qabıl etildi (Accepted)',
    entityType: 'task',
    entityId: 'tsk-104',
    entityName: 'Toqımashılıq kásip-óneri oqıtıw',
    changes: [
      { field: 'status', oldValue: 'under_review', newValue: 'accepted' },
      { field: 'completedDate', oldValue: 'bos', newValue: '2026-09-24' },
    ],
    reason: '40 nafar pútkeriwshi klasterge jumısqa kirgenligi tastıyıqlandı',
    ipAddress: '195.158.12.84',
  },
];

export const mockIndicators: SectorIndicator[] = [
  {
    id: 'ind-1',
    code: 'IND-SAN-01',
    name: {
      qq: 'Sanaat islep shıǵarıwı kólemi (mlrd som)',
      uz: 'Sanoat ishlab chiqarish hajmi (mlrd so\'m)',
      ru: 'Объем промышленного производства (млрд сум)',
    },
    sectorKey: 'industry',
    sectorName: { qq: 'Sanaat', uz: 'Sanoat', ru: 'Промышленность' },
    unit: 'mlrd som',
    historical: { '2023': 240.5, '2024': 285.2, '2025': 324.0, '2026': 368.5 },
    trendPercent: 13.7,
    isPositiveTrend: true,
  },
  {
    id: 'ind-2',
    code: 'IND-INV-01',
    name: {
      qq: 'Tiykarǵı kapitalǵa ózlestirilgen investiciyalar (mlrd som)',
      uz: 'Asosiy kapitalga o\'zlashtirilgan investitsiyalar (mlrd so\'m)',
      ru: 'Инвестиции в основной капитал (млрд сум)',
    },
    sectorKey: 'investments',
    sectorName: { qq: 'Investiciyalar', uz: 'Investitsiyalar', ru: 'Инвестиции' },
    unit: 'mlrd som',
    historical: { '2023': 185.0, '2024': 245.8, '2025': 310.2, '2026': 385.0 },
    trendPercent: 24.1,
    isPositiveTrend: true,
  },
  {
    id: 'ind-3',
    code: 'IND-AGR-01',
    name: {
      qq: 'Awıl xojalıǵı ónimleri jalpı kólemi (mlrd som)',
      uz: 'Qishloq xo\'jaligi mahsulotlari yalpi hajmi (mlrd so\'m)',
      ru: 'Валовая продукция сельского хозяйства (млрд сум)',
    },
    sectorKey: 'agriculture',
    sectorName: { qq: 'Awıl xojalıǵı', uz: 'Qishloq xo\'jaligi', ru: 'Сельское хозяйство' },
    unit: 'mlrd som',
    historical: { '2023': 410.2, '2024': 465.0, '2025': 515.6, '2026': 570.4 },
    trendPercent: 10.6,
    isPositiveTrend: true,
  },
  {
    id: 'ind-4',
    code: 'IND-EMP-01',
    name: {
      qq: 'Dáreklik jańa jumıs orınları sanı (birlik)',
      uz: 'Yaratilgan yangi doimiy ish o\'rinlari (birlik)',
      ru: 'Создано новых постоянных рабочих мест (единиц)',
    },
    sectorKey: 'employment',
    sectorName: { qq: 'Bántlik', uz: 'Bandlik', ru: 'Занятость' },
    unit: 'birlik',
    historical: { '2023': 850, '2024': 1120, '2025': 1340, '2026': 1580 },
    trendPercent: 17.9,
    isPositiveTrend: true,
  },
  {
    id: 'ind-5',
    code: 'IND-SRV-01',
    name: {
      qq: 'Kórsetilgen bazar xızmetleri kólemi (mlrd som)',
      uz: 'Ko\'rsatilgan bozor xizmatlari hajmi (mlrd so\'m)',
      ru: 'Объем оказанных рыночных услуг (млрд сум)',
    },
    sectorKey: 'services',
    sectorName: { qq: 'Xızmetler', uz: 'Xizmatlar', ru: 'Услуги' },
    unit: 'mlrd som',
    historical: { '2023': 112.0, '2024': 138.4, '2025': 165.2, '2026': 198.0 },
    trendPercent: 19.8,
    isPositiveTrend: true,
  },
  {
    id: 'ind-6',
    code: 'IND-TAX-01',
    name: {
      qq: 'Jergilikli byudjet salıq tushumları (mlrd som)',
      uz: 'Mahalliy byudjet soliq tushumlari (mlrd so\'m)',
      ru: 'Налоговые поступления местного бюджета (млрд сум)',
    },
    sectorKey: 'budget',
    sectorName: { qq: 'Byudjet', uz: 'Byudjet', ru: 'Бюджет' },
    unit: 'mlrd som',
    historical: { '2023': 42.5, '2024': 51.0, '2025': 60.8, '2026': 73.2 },
    trendPercent: 20.4,
    isPositiveTrend: true,
  },
];
